name: master

on:
  push:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.*
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test code
      run: go test -v ./...
