name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag mtharrison/github-pr-comment-resource:${{steps.vars.outputs.tag}}

    - name: Push the tagged Docker image
      run: docker push mtharrison/github-pr-comment-resource:${{steps.vars.outputs.tag}}
